#############Secrets configuration
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: k8s-program
type: Opaque
data:
  POSTGRES_USER_DB_USERNAME: user
  POSTGRES_USER_DB_PASSWORD: password
  POSTGRES_POST_DB_USERNAME: post
  POSTGRES_POST_DB_PASSWORD: password
---